//jshint esversion:6

const CompassBoxes = [
  {
    title: "Geometry Boxes",
    img: "/img/Headers/1.png",
  },
  {
    id: 112,
    name: "Stylo Senior",
    Secondary: "Best Seller Geometry Box",
    Contents:
      "0.7 MM Pencil with Lead Box, Style Glue Gum, Diamond Compass Set with Quality drawing Set, Sharpener, Eraser Stylo White Adhesive.",
    WithGST: 57.0,
    MRP: "98.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 110,
    name: "Stylo Junior",
    Secondary: "Best Seller Geometry Box",
    Contents:
      "C Type Box, Diamond Compass, Half Pencil, Adhesive Tape, Drawing Set, Time Table, Sharpener, Eraser",
    WithGST: 45.0,
    MRP: "77.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 111,
    name: "Stylo Kids",
    Secondary: "Best Seller Geometry Box",
    Contents:
      "Full Plastic Tray, Drawing Set, Diamond Compass Set, Half Pencil, Eraser",
    WithGST: 33.0,
    MRP: "57.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 101,
    name: "Benzo",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box with Coloured Bottom, Extra Edition Quality Drawing Set, Plastic Compass Set with self cantering point, Whitener, Sharpener, Eraser, Correction Pen, 0.7 MM Pencil with Lead, Half Wooden Pencil.",
    WithGST: 102.0,
    MRP: "170.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 102,
    name: "Creta",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box with Coloured Bottom, Extra Edition Quality Drawing Set, Plastic Compass Set with self cantering point, Long tube Gum, Snakes & Ladder and Ludo.",
    WithGST: 60.0,
    MRP: "102.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 3,
  },
  {
    id: 103,
    name: "Growline",
    Secondary: "Geometry Box",
    Contents:
      "Full Plastic Tray, Drawing Set, Diamond Compass Set, Eraser, Half Pencil, Full S.S. Scissor, Sharpener, Cello Tape.",
    WithGST: 51.0,
    MRP: "92.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 104,
    name: "Jackpot",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box, Drawing Set, Compass Set, Sharpener, Eraser, Stencil, D.F. Ball Pen",
    WithGST: 45.0,
    MRP: "78.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 105,
    name: "Leader (Special Edition)",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box with Coloured Bottom, Extra Edition Quality Drawing Set, Plastic Compass Set with self cantering point, Sharpener, Eraser, CD Marker Pen, Highlighter, Glue Stick. ",
    WithGST: 92.0,
    MRP: "160.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 106,
    name: "Optima",
    Secondary: "Geometry Box",
    Contents:
      "Broad Tin Box, Full Moulding Net, Compass Set, Quality Drawing Set, Eraser, Sharpener, 0.7 MM Pencil",
    WithGST: 40.0,
    MRP: "70.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 113,
    name: "Vidyarthi",
    Secondary: "Geometry Box",
    Contents:
      "C Type Box, Full Net, Compass Set, Quality Drawing Set, Eraser, Sharpener, Half Pencil",
    WithGST: 38.0,
    MRP: "68.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 109,
    name: "Save Nature Series",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box, Drawing Set, Compass Set, Sharpener, Eraser, Stencil, D.F. Ball Pen",
    WithGST: 43.0,
    MRP: "75.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 108,
    name: "Platinum",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box with Coloured Bottom, Extra Edition Quality Drawing Set, Plastic Compass Set with self cantering point, Quality Drawing Set, 2 MM Lead Pencil, 10 MM Stencil, Sharpener, Eraser. ",
    WithGST: 73.0,
    MRP: "110.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
  {
    id: 107,
    name: "Oster",
    Secondary: "Geometry Box",
    Contents:
      "High Quality Box with Coloured Bottom, Extra Edition Quality Drawing Set, Plastic Compass Set with self cantering point, Ball Pen, Binder Clip, 3 in 1 Sharpener",
    WithGST: 53.0,
    MRP: "96.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "16",
    TotalItems: "16 x 10 = 160",
    imgCount: 2,
  },
];

const Compass = [
  {
    title: "Compass",
    img: "/img/Headers/2.png",
  },
  {
    id: 202,
    name: "Stylo Compass Black-333",
    Secondary: "Mathematical Instrument",
    Contents: "1 Compass Black 333",
    WithGST: 46.0,
    MRP: "150.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "100",
    TotalItems: "10 x 100 = 1000",
    imgCount: 4,
  },
  {
    id: 201,
    name: "Stylo Benzo Compass",
    Secondary: "Mathematical Instrument",
    Contents: "1 Benzo Compass",
    WithGST: 62.75,
    MRP: "200.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "100",
    TotalItems: "10 x 100 = 1000",
    imgCount: 4,
  },
  {
    id: 204,
    name: "Stylo Optus Compass",
    Secondary: "Mathematical Instrument",
    Contents: "1 Diamond Compass 555",
    WithGST: 67.25,
    MRP: "150.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "100",
    TotalItems: "10 x 100 = 1000",
    imgCount: 4,
  },
  {
    id: 203,
    name: "Stylo Diamond Compass-555",
    Secondary: "Mathematical Instrument",
    Contents: "1 Optus Compass",
    WithGST: 71.75,
    MRP: "250.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "100",
    TotalItems: "10 x 100 = 1000",
    imgCount: 4,
  },
];

const Dusters = [
  {
    title: "Dusters",
    img: "/img/Headers/3.png",
  },
  {
    id: 301,
    name: "Duster DWF/DGF 000",
    Secondary: null,
    Contents: "10 Wooden DGF/DWF 000 Dusters",
    WithGST: 87.5,
    MRP: "250.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "90-100",
    TotalItems: "10 x 100 = 1000",
    imgCount: 2,
  },
  {
    id: 302,
    name: "Duster DWF/DGF 111",
    Secondary: null,
    Contents: "10 Wooden DGF/DWF 111 Dusters",
    WithGST: 151.25,
    MRP: "350.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "50",
    TotalItems: "10 x 50 = 500",
    imgCount: 2,
  },
  {
    id: 303,
    name: "Duster DWF/DGF 222",
    Secondary: null,
    Contents: "10 Wooden DGF/DWF 222 Dusters",
    WithGST: 180.0,
    MRP: "400.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "50",
    TotalItems: "10 x 50 = 500",
    imgCount: 2,
  },
  {
    id: 304,
    name: "Duster DWF/DGF 333 (T)",
    Secondary: null,
    Contents: "10 Wooden DGF/DWF 333 Dusters",
    WithGST: 180.0,
    MRP: "400.00 per Box",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "50",
    TotalItems: "10 x 50 = 500",
    imgCount: 2,
  },
];

const Erasers = [
  {
    title: "Erasers",
    img: "/img/Headers/4.png",
  },
  {
    id: 401,
    name: "Stylo Eraser",
    Secondary: "20 Pieces per Box",
    Contents: "20 Erasers",
    WithGST: 21.65,
    MRP: "60.00",
    UnitsPerBox: 20,
    BoxToCarton: "No",
    BoxesPerCarton: "200",
    TotalItems: "20 x 200 = 4000",
    imgCount: 3,
  },
  {
    id: 402,
    name: "3 in 1 Triangular Eraser (Small)",
    Secondary: "Jar Pack - 100 Pieces",
    Contents: "100 3-in-1 Triangular Erasers Small Size",
    WithGST: 46.85,
    MRP: "150.00",
    UnitsPerBox: 100,
    BoxToCarton: "No",
    BoxesPerCarton: "72 Jars",
    TotalItems: "100 x 72 = 7200",
    imgCount: 3,
  },
  {
    id: 403,
    name: "3 in 1 Triangular Eraser (Big)",
    Secondary: "Jar Pack - 100 Pieces",
    Contents: "100 3-in-1 Triangular Erasers Big Size",
    WithGST: 93.7,
    MRP: "300.00",
    UnitsPerBox: 100,
    BoxToCarton: "No",
    BoxesPerCarton: "40 Jars",
    TotalItems: "100 x 40 = 4000",
    imgCount: 3,
  },
];

const Chalk = [
  {
    title: "Chalks",
    img: "/img/Headers/5.png",
  },
  {
    id: 501,
    name: "Stylo Dustless Chalk",
    Secondary: "50 Pieces per box",
    Contents: "50 Dustless Chalks",
    WithGST: 13.0,
    MRP: "35.00",
    UnitsPerBox: null,
    BoxToCarton: "No",
    BoxesPerCarton: "60",
    TotalItems: "50 x 60 = 3000",
    imgCount: 2,
  },
];

const Pencil = [
  {
    title: "Pencil",
    img: "/img/Headers/6.png",
  },
  {
    id: 601,
    name: "Stylo 0.7 Lead Pencil",
    Secondary: "10 Pieces Per Pouch, 10 Lead Boxes (with 10 refills each)",
    Contents: "10 0.7 MM Lead Pencil with 10 Lead Boxes each with 10 refills.",
    WithGST: 32.5,
    MRP: null,
    UnitsPerBox: 20.0,
    BoxToCarton: "No",
    BoxesPerCarton: "20",
    TotalItems: "10 x 20 x 20 = 4000 Pencils; 10 x 20 x 20 = 4000 Lead Box",
  },
];

const Clipboard = [
  {
    title: "Clipboard",
    img: "/img/Headers/7.png",
  },
  {
    id: 701,
    name: "Stylo Transparent Unbreakable Clipboard",
    Secondary: "Clipboard",
    Contents: "10 Transparent Unbreakable Clipboards",
    WithGST: 65.0,
    MRP: "1400.00",
    UnitsPerBox: 10.0,
    BoxToCarton: "Yes",
    BoxesPerCarton: "12",
    TotalItems: "10 x 12 = 120",
  },
];

module.exports = [
  CompassBoxes,
  Compass,
  Dusters,
  Erasers,
  Chalk,
  Pencil,
  Clipboard,
];
